package JavaREST.Framework;

/**
 * Author: Keith Jackson
 * Date: 4/18/2016
 * License: MIT
 *
 */

public enum HttpStatusCode {
    OK, CONTINUE, SWITCHING_PROTOCOLS, CREATED, ACCEPTED, NON_AUTHORITATIVE_INFORMATION, NO_CONTENT, RESET_CONTENT,
    PARTIAL_CONTENT, MULTIPLE_CHOICES, MOVED_PERMANENTLY, FOUND, SEE_OTHER, NOT_MODIFIED, USE_PROXY, TEMPORARY_REDIRECT,
    BAD_REQUEST, UNAUTHORIZED, PAYMENT_REQUIRED, FORBIDDEN, NOT_FOUND, METHOD_NOT_FOUND, NOT_ACCEPTABLE,
    PROXY_AUTHENTICATION_REQUIRED, REQUEST_TIMEOUT, CONFLICT, GONE, LENGTH_REQUIRED, EXPECTATION_FAILED,
    REQUESTED_RANGE_NOT_SATISFIABLE, UNSUPPORTED_MEDIA_TYPE, REQUEST_URI_TOO_LONG, REQUEST_ENTITY_TOO_LARGE,
    PRECONDITION_FAILED, SERVICE_UNAVAILABLE, BAD_GATEWAY, NOT_IMPLEMENTED, INTERNAL_SERVER_ERROR, GATEWAY_TIMEOUT,
    HTTP_VERSION_NOT_SUPPORTED, RESUME_INCOMPLETE, NETWORK_AUTHENTICATION_REQUIRED, UNPROCESSABLE_ENTITY,
}
